const CARS={rookie:{price:0,max:260,handling:1.25,brake:3.2},comet:{price:250,max:290,handling:1.4,brake:3.7},vortex:{price:600,max:320,handling:1.6,brake:4.1},phantom:{price:1200,max:350,handling:1.8,brake:4.6}};
const TRACKS=['sunset','city','desert','forest','snow'];
const MISSIONS=[{id:'pass20',key:'passed',target:20,reward:75},{id:'survive120',key:'seconds',target:120,reward:150},{id:'coins30',key:'coins',target:30,reward:100},{id:'near5',key:'near',target:5,reward:100}];
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})}
function db(env){if(!env.DB)throw Error('Database unavailable');return env.DB}
async function profile(env,id){await db(env).prepare('INSERT OR IGNORE INTO players (id,name) VALUES (?,?)').bind(id,'Racer '+id.replace(/[^a-z0-9]/gi,'').slice(-4)).run();return db(env).prepare('SELECT * FROM players WHERE id=?').bind(id).first()}
function view(p){return {name:p.name,coins:p.coins,best:p.best,garage:JSON.parse(p.garage),missions:JSON.parse(p.missions)}}
async function api(request,env){const url=new URL(request.url),path=url.pathname,id=request.headers.get('oai-authenticated-user-id');if(!id)return json({error:'Sign in to save your progress.'},401);
if(request.method==='POST'&&request.headers.get('Origin')!==url.origin)return json({error:'Invalid request origin.'},403);
if(request.method==='GET'&&path==='/api/profile')return json(view(await profile(env,id)));
if(request.method==='GET'&&path==='/api/leaderboard'){const r=await db(env).prepare('SELECT name,best,id FROM players WHERE best>0 ORDER BY best DESC,name ASC LIMIT 20').all();return json({entries:r.results.map((p,i)=>({rank:i+1,name:p.name,score:p.best,you:p.id===id}))})}
if(request.method!=='POST')return json({error:'Not found'},404);
if(Number(request.headers.get('content-length')||0)>4096)return json({error:'Request too large'},413);const raw=await request.text();if(raw.length>4096)return json({error:'Request too large'},413);let b;try{b=JSON.parse(raw)}catch{return json({error:'Invalid JSON'},400)}if(!b||typeof b!=='object'||Array.isArray(b))return json({error:'Invalid request'},400);
const p=await profile(env,id);
if(path==='/api/name'){if(typeof b.name!=='string'||!/^[\p{L}\p{N} _-]{2,20}$/u.test(b.name.trim()))return json({error:'Use 2–20 letters, numbers, spaces, underscores or hyphens.'},400);await db(env).prepare('UPDATE players SET name=? WHERE id=?').bind(b.name.trim(),id).run();return json(view(await profile(env,id)))}
if(path==='/api/purchase'){const garage=JSON.parse(p.garage);if(!CARS[b.car])return json({error:'Unknown car'},400);let cost;if(b.kind==='car'){if(garage.owned.includes(b.car))return json(view(p));cost=CARS[b.car].price;garage.owned.push(b.car)}else if(b.kind==='upgrade'&&['engine','handling','brakes'].includes(b.upgrade)){if(!garage.owned.includes(b.car))return json({error:'Unlock this car first.'},400);garage.upgrades[b.car]??={};let level=garage.upgrades[b.car][b.upgrade]||0;if(level>=3)return json({error:'Already fully upgraded.'},400);cost=(level+1)*100;garage.upgrades[b.car][b.upgrade]=level+1}else return json({error:'Invalid purchase'},400);
const result=await db(env).prepare('UPDATE players SET coins=coins-?,garage=? WHERE id=? AND coins>=? AND garage=?').bind(cost,JSON.stringify(garage),id,cost,p.garage).run();if(!result.meta.changes)return json({error:'Not enough coins, or your garage changed. Refresh and try again.'},409);return json(view(await profile(env,id)))}
if(path==='/api/run/start'){if(!CARS[b.car]||!JSON.parse(p.garage).owned.includes(b.car)||!TRACKS.includes(b.track))return json({error:'Choose an unlocked car and a valid track.'},400);const runId=crypto.randomUUID();await db(env).prepare('INSERT INTO runs (id,player_id,started,car,track) VALUES (?,?,?,?,?)').bind(runId,id,Date.now(),b.car,b.track).run();return json({runId})}
if(path==='/api/run/finish'){if(typeof b.runId!=='string')return json({error:'Missing run'},400);const r=await db(env).prepare('SELECT * FROM runs WHERE id=? AND player_id=?').bind(b.runId,id).first();if(!r)return json({error:'Run not found'},404);if(r.finished!==null)return json({...view(p),alreadySaved:true});const s=b.stats;if(!s||!['score','seconds','coins','passed','near'].every(k=>Number.isFinite(s[k])&&s[k]>=0))return json({error:'Invalid race result'},400);const seconds=Math.min(s.seconds,(Date.now()-r.started)/1000+3);if(s.seconds>seconds+1||s.score>seconds*220+1000||s.coins>seconds*8+10||s.passed>seconds*3+3||s.near>s.passed)return json({error:'Race result is outside the supported limits.'},400);
const done=JSON.parse(p.missions),newMissions=MISSIONS.filter(m=>!done.includes(m.id)&&s[m.key]>=m.target);let reward=Math.floor(s.coins)+newMissions.reduce((a,m)=>a+m.reward,0);const finalScore=Math.floor(s.score);
await db(env).batch([db(env).prepare('UPDATE players SET coins=coins+?,best=MAX(best,?),missions=? WHERE id=? AND EXISTS (SELECT 1 FROM runs WHERE id=? AND player_id=? AND finished IS NULL)').bind(reward,finalScore,JSON.stringify([...done,...newMissions.map(m=>m.id)]),id,b.runId,id),db(env).prepare('UPDATE runs SET finished=?,score=? WHERE id=? AND player_id=? AND finished IS NULL').bind(Date.now(),finalScore,b.runId,id)]);return json({...view(await profile(env,id)),reward,newMissions:newMissions.map(m=>m.id)})}
return json({error:'Not found'},404)}
export default {async fetch(request,env){try{let path=new URL(request.url).pathname;if(path.startsWith('/api/'))return await api(request,env);if(request.method!=='GET'&&request.method!=='HEAD')return new Response('Method not allowed',{status:405});const asset=ASSETS[path==='/'?'/index.html':path];if(!asset)return new Response('Not found',{status:404});return new Response(request.method==='HEAD'?null:asset.body,{headers:{'Content-Type':asset.type,'Cache-Control':'no-cache','X-Content-Type-Options':'nosniff'}})}catch(e){console.error('Apex Rush request failed',e);return json({error:'Could not reach your saved progress. Please try again.'},503)}}};
